name: Bump

on:
  workflow_dispatch:
  schedule:
    - cron: "25 0-23/8 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/LICENSE"
      - "**/README.md"
      - "**/got_github_release.sh"
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Bump"
  Bump:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set some variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "REPO_URL=github.com/${{ github.repository }}" >> $GITHUB_ENV
          echo "checksec_sh_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/slimm609/checksec.sh/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "bashrc_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/IceCodeNew/myrc/commits?per_page=1&path=.bashrc' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "shadowsocks_rust_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/shadowsocks/shadowsocks-rust/commits?per_page=1' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "b3sum_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/BLAKE3-team/BLAKE3/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "fd_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/sharkdp/fd/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "bat_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/sharkdp/bat/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "hexyl_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/sharkdp/hexyl/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "hyperfine_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/sharkdp/hyperfine/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "desed_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/SoptikHa2/desed/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "fnm_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/Schniz/fnm/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "checksec_rs_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/etke/checksec.rs/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "boringtun_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/cloudflare/boringtun/commits?per_page=1' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "RUST_VERSION=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/rust-lang/rust/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "cachebust=$(date +%s)" >> $GITHUB_ENV
          echo "rust_nightly_date=$(TZ=':Asia/Taipei' date +%F)" >> $GITHUB_ENV
        shell: bash
      # Runs a set of commands using the runners shell
      - name: Bump
        run: |
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git reset --hard origin/master
          sed -i -E "s/^ARG checksec_sh_latest_tag_name=.+/ARG checksec_sh_latest_tag_name=${checksec_sh_latest_tag_name:?empty value}/" build_base_alpine.Dockerfile build_base_ubuntu.Dockerfile nightly_build_base_alpine.Dockerfile nightly_build_base_ubuntu.Dockerfile
          sed -i -E "s/^ARG bashrc_latest_commit_hash=.+/ARG bashrc_latest_commit_hash=${bashrc_latest_commit_hash:?empty value}/" build_base_alpine.Dockerfile build_base_ubuntu.Dockerfile nightly_build_base_alpine.Dockerfile nightly_build_base_ubuntu.Dockerfile
          sed -i -E "s/^ARG shadowsocks_rust_latest_commit_hash=.+/ARG shadowsocks_rust_latest_commit_hash=${shadowsocks_rust_latest_commit_hash:?empty value}/" Dockerfile
          sed -i -E "s/^ARG b3sum_latest_tag_name=.+/ARG b3sum_latest_tag_name=${b3sum_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG fd_latest_tag_name=.+/ARG fd_latest_tag_name=${fd_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG bat_latest_tag_name=.+/ARG bat_latest_tag_name=${bat_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG hexyl_latest_tag_name=.+/ARG hexyl_latest_tag_name=${hexyl_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG hyperfine_latest_tag_name=.+/ARG hyperfine_latest_tag_name=${hyperfine_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG desed_latest_tag_name=.+/ARG desed_latest_tag_name=${desed_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG fnm_latest_tag_name=.+/ARG fnm_latest_tag_name=${fnm_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG checksec_rs_latest_tag_name=.+/ARG checksec_rs_latest_tag_name=${checksec_rs_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG boringtun_latest_commit_hash=.+/ARG boringtun_latest_commit_hash=${boringtun_latest_commit_hash:?empty value}/" Dockerfile
          sed -i -E "s/^ENV RUST_VERSION=.+/ARG RUST_VERSION=${RUST_VERSION:?empty value}/" build_base_alpine.Dockerfile build_base_ubuntu.Dockerfile nightly_build_base_alpine.Dockerfile nightly_build_base_ubuntu.Dockerfile
          sed -i -E "s/^ARG cachebust=.+/ARG cachebust=${cachebust:?empty value}/" Dockerfile
          sed -i -E "s/^ARG rust_nightly_date=.+/ARG rust_nightly_date=${rust_nightly_date:?empty value}/" build_base_alpine.Dockerfile build_base_ubuntu.Dockerfile nightly_build_base_alpine.Dockerfile nightly_build_base_ubuntu.Dockerfile
          git add Dockerfile build_base_alpine.Dockerfile build_base_ubuntu.Dockerfile nightly_build_base_alpine.Dockerfile nightly_build_base_ubuntu.Dockerfile
          git commit -m "Bump"
          git push -u origin master
      - name: Force push `release` branch
        run: |
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git checkout release
          git reset --hard origin/master
          git rm got_github_release.sh release.Dockerfile build_base_alpine.Dockerfile build_base_ubuntu.Dockerfile nightly_build_base_alpine.Dockerfile nightly_build_base_ubuntu.Dockerfile
          git rm -r .github
          git commit -m "${{ env.RELEASE_NAME }}"
          git push -f -u origin release
      - name: Force push `build_base` branch
        run: |
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git checkout build_base
          git reset --hard origin/master
          git rm got_github_release.sh Dockerfile release.Dockerfile
          git rm -r .github
          git commit -m "${{ env.RELEASE_NAME }}"
          git push -f -u origin build_base
