name: Bump

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0-23/12 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/LICENSE"
      - "**/README.md"
      - "**/got_github_release.sh"
  # pull_request:
  #   branches:
  #     - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Bump"
  Bump:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set some variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "REPO_URL=github.com/${{ github.repository }}" >> $GITHUB_ENV
          echo "shadowsocks_rust_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/shadowsocks/shadowsocks-rust/commits?per_page=1' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "boringtun_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/cloudflare/boringtun/commits?per_page=1' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "cfnts_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/cloudflare/cfnts/commits?per_page=1' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "rsign2_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/jedisct1/rsign2/commits?per_page=1' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "b3sum_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/BLAKE3-team/BLAKE3/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "ripgrep_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/BurntSushi/ripgrep/commits?per_page=1' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "coreutils_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/uutils/coreutils/commits?per_page=1' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "sd_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/chmln/sd/commits?per_page=1' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "fd_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/sharkdp/fd/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "bat_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/sharkdp/bat/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "hexyl_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/sharkdp/hexyl/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "hyperfine_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/sharkdp/hyperfine/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "fnm_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/Schniz/fnm/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "checksec_rs_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/etke/checksec.rs/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "dog_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/ogham/dog/commits?per_page=1' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "websocat_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/vi/websocat/commits?per_page=1' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "just_latest_commit_hash=$(curl -sL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/casey/just/commits?per_page=1' |
                grep -Fm1 'sha' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "desed_latest_tag_name=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/SoptikHa2/desed/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "RUST_VERSION=$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/rust-lang/rust/releases/latest' |
                grep -F 'tag_name' | cut -d'"' -f4)" >> $GITHUB_ENV
          echo "cachebust=$(date +%s)" >> $GITHUB_ENV
          echo "rust_nightly_date=$(TZ=':Asia/Taipei' date +%F)" >> $GITHUB_ENV
        shell: bash
      # Runs a set of commands using the runners shell
      - name: Force push `release` branch
        run: |
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git checkout release
          git reset --hard origin/master
          sed -i -E "s/^ARG shadowsocks_rust_latest_commit_hash=.+/ARG shadowsocks_rust_latest_commit_hash=${shadowsocks_rust_latest_commit_hash:?empty value}/" Dockerfile
          sed -i -E "s/^ARG boringtun_latest_commit_hash=.+/ARG boringtun_latest_commit_hash=${boringtun_latest_commit_hash:?empty value}/" Dockerfile
          sed -i -E "s/^ARG cfnts_latest_commit_hash=.+/ARG cfnts_latest_commit_hash=${cfnts_latest_commit_hash:?empty value}/" Dockerfile
          sed -i -E "s/^ARG rsign2_latest_commit_hash=.+/ARG rsign2_latest_commit_hash=${rsign2_latest_commit_hash:?empty value}/" Dockerfile
          sed -i -E "s/^ARG b3sum_latest_tag_name=.+/ARG b3sum_latest_tag_name=${b3sum_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG ripgrep_latest_commit_hash=.+/ARG ripgrep_latest_commit_hash=${ripgrep_latest_commit_hash:?empty value}/" Dockerfile
          sed -i -E "s/^ARG coreutils_latest_commit_hash=.+/ARG coreutils_latest_commit_hash=${coreutils_latest_commit_hash:?empty value}/" Dockerfile
          sed -i -E "s/^ARG sd_latest_commit_hash=.+/ARG sd_latest_commit_hash=${sd_latest_commit_hash:?empty value}/" Dockerfile
          sed -i -E "s/^ARG fd_latest_tag_name=.+/ARG fd_latest_tag_name=${fd_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG bat_latest_tag_name=.+/ARG bat_latest_tag_name=${bat_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG hexyl_latest_tag_name=.+/ARG hexyl_latest_tag_name=${hexyl_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG hyperfine_latest_tag_name=.+/ARG hyperfine_latest_tag_name=${hyperfine_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG fnm_latest_tag_name=.+/ARG fnm_latest_tag_name=${fnm_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG checksec_rs_latest_tag_name=.+/ARG checksec_rs_latest_tag_name=${checksec_rs_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG dog_latest_commit_hash=.+/ARG dog_latest_commit_hash=${dog_latest_commit_hash:?empty value}/" Dockerfile
          sed -i -E "s/^ARG websocat_latest_commit_hash=.+/ARG websocat_latest_commit_hash=${websocat_latest_commit_hash:?empty value}/" Dockerfile
          sed -i -E "s/^ARG just_latest_commit_hash=.+/ARG just_latest_commit_hash=${just_latest_commit_hash:?empty value}/" Dockerfile
          sed -i -E "s/^ARG desed_latest_tag_name=.+/ARG desed_latest_tag_name=${desed_latest_tag_name:?empty value}/" Dockerfile
          sed -i -E "s/^ARG cachebust=.+/ARG cachebust=${cachebust:?empty value}/" Dockerfile
          git add Dockerfile
          git rm got_github_release.sh release.Dockerfile build_base_alpine.Dockerfile build_base_ubuntu.Dockerfile
          git rm -r .github
          git commit -m "${{ env.RELEASE_NAME }}"
          git push -f origin HEAD:release
      - name: Force push `build_base` branch
        run: |
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git checkout build_base
          git reset --hard origin/master
          sed -i -E "s/^    RUST_VERSION=.+/    RUST_VERSION=${RUST_VERSION:?empty value} \\\\/" build_base_alpine.Dockerfile build_base_ubuntu.Dockerfile
          sed -i -E "s/^ENV rust_nightly_date=.+/ENV rust_nightly_date=${rust_nightly_date:?empty value} \\\\/" build_base_alpine.Dockerfile build_base_ubuntu.Dockerfile
          git add build_base_alpine.Dockerfile build_base_ubuntu.Dockerfile
          git rm got_github_release.sh Dockerfile release.Dockerfile
          git rm -r .github
          git commit -m "${{ env.RELEASE_NAME }}"
          git push -f origin HEAD:build_base
