name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: "5 17 * * *"
  # label:
  #   types: [created, deleted]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'latest-release'
          path: './oldrelease'
          fetch-depth: 0
      - name: Set some variables
        run: |
          echo "RELEASE_NAME=$(TZ='Asia/Taipei' date --rfc-3339=seconds) [""$(curl -sSL -H 'Accept: application/vnd.github.v3+json' \
                'https://api.github.com/repos/IceCodeNew/rust-collection/commits?per_page=1&sha=release' |
                grep -Fm1 'sha' | cut -d'"' -f4)""]" >> $GITHUB_ENV
        shell: bash
      - name: Move files to publish directory
        run: |
          pushd oldrelease || exit 1
          while [[ $(wc -l < ./releases.txt) -ge 15 ]]; do
            git push -d origin "$(head -n 1 ./releases.txt)"
            sed -i '1d' ./releases.txt
          done
          echo "$(TZ='Asia/Taipei' date +%F-%H-%M-%S-%Z)" >> ./releases.txt
          popd
          mkdir -p ./publish/usr/share/caddy/
          cp -f ./oldrelease/releases.txt ./publish/
          docker create -it --name dummy quay.io/icecodenew/rust-collection:latest bash
          docker cp dummy:/usr/local/cargo/bin/ ./publish/assets
          docker rm -f dummy
          docker rmi -f quay.io/icecodenew/rust-collection:latest
      - name: Git push assets to "latest-release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$(TZ='Asia/Taipei' date +%F-%H-%M-%S-%Z)"
          git add -A
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add rust-collection "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f rust-collection HEAD:latest-release
          git push -f rust-collection HEAD:"$(TZ='Asia/Taipei' date +%F-%H-%M-%S-%Z)"
      - name: Purge jsdelivr CDN
        run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@latest-release/${file}"
          done
